"""add-relationships-in- document-sections-table” 
'


Revision ID: c26689e81a1d
Revises: 2c6d2009d58a
Create Date: 2026-09-06 19:12:54.454740

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c26689e81a1d'
down_revision: Union[str, Sequence[str], None] = '2c6d2009d58a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""

    op.create_table(
        'document_sections',
        sa.Column('id', sa.UUID(), nullable=False),
        sa.Column('document_id', sa.UUID(), nullable=False),
        sa.Column('section_name', sa.Text(), nullable=True),
        sa.Column('content', sa.Text(), nullable=False),
        sa.Column(
            'created_at',
            sa.DateTime(timezone=True),
            server_default=sa.text('now()'),
            nullable=False,
        ),
        sa.Column(
            'updated_at',
            sa.DateTime(timezone=True),
            server_default=sa.text('now()'),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ['document_id'],
            ['documents.id'],
        ),
        sa.PrimaryKeyConstraint('id'),
    )

    op.add_column(
        'document_chunks',
        sa.Column('section_id', sa.UUID(), nullable=True),
    )

    op.execute("DELETE FROM document_chunks")

    op.alter_column(
        'document_chunks',
        'section_id',
        nullable=False,
    )

    op.create_foreign_key(
        None,
        'document_chunks',
        'document_sections',
        ['section_id'],
        ['id'],
    )

    op.drop_column(
        'document_chunks',
        'section_name',
    )
def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('document_chunks', sa.Column('section_name', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'document_chunks', type_='foreignkey')
    op.drop_column('document_chunks', 'section_id')
    op.drop_table('document_sections')
    # ### end Alembic commands ###
